version: "3.3"
services:
  main:
    build: .
    environment:
      - GRAPH_HOST=graph
      - GRAPH_GRAPH=graph
      - GRAPH_PORT=8182
    depends_on:
      - graph
    volumes:
      - .:/usr/src/advent

  graph:
    build:
      context: inf/graph
