version: "3.3"
services:
  main:
    build: .
    environment:
      - GRAPH_HOST=graph
      - GRAPH_GRAPH=rules
      - GRAPH_PORT=8182
    depends_on:
      - graph

  graph:
    build:
      context: inf/graph
