name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Build docker-compose stack
      run: docker-compose up -d

    - name: Run test suite
      run: docker-compose run main composer run-script test
